### ISSUE TITLE
500: INTERNAL_SERVER_ERROR Code: FUNCTION_INVOCATION_FAILED

### ISSUE THREAD

**Issue by leonguyen52** [tbdsux/kuryana#24]
Hi there,

I got the following error while loading content with MDL slug. 
https://kuryana.vercel.app/id/716895-zui-shi-ren-jian-yan-huo-se

Can you help to take a look?

[ERROR] AttributeError: 'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/var/task/vc__handler__python.py", line 305, in vc_handler
    response = asgi_cycle(__vc_module.app, body)
  File "/var/task/vc__handler__python.py", line 208, in __call__
    loop.run_until_complete(asgi_task)
  File "/var/lang/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/var/task/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/var/task/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/var/task/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/var/task/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/var/task/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/var/task/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/var/task/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/var/task/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/var/task/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/var/task/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/var/task/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/var/task/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/var/task/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/var/task/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "./api/main.py", line 39, in fetch
    code, r = await fetch_func(query=drama_id, t="drama")
  File "/var/task/api/utils.py", line 45, in fetch_func
    f._get()
  File "/var/task/api/fetch.py", line 82, in _get
    self._get_main_container()
  File "/var/task/api/fetch.py", line 35, in _get_main_container
    container.find("div", class_="show-synopsis")

**Comment by leonguyen52** [comment]
Only facing error while getting DRAMA Info, for other part like casts, it worked well.
https://kuryana.vercel.app/id/716895-zui-shi-ren-jian-yan-huo-se/cast

**Comment by leonguyen52** [comment]
I fixed it my self by editing the fetch.py file at line 35. This issue caused by blank synopsis. My code changed to:
# SYNOPSIS
        synopsis = container.find("div", class_="show-synopsis").find("span")
        self.info["synopsis"] = synopsis.text.replace("\n", " ") if synopsis else "No synopsis available"
