### ISSUE TITLE
500: INTERNAL_SERVER_ERROR while searching but no result

### ISSUE THREAD

**Issue by leonguyen52** [tbdsux/kuryana#26]
Trying to search for a drama but it's not available on MDL yet then it will return error:

500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: sin1::hz578-1678765839345-26a0508481ef

- Keyword: 你好我的对面男友
- Testing link: https://kuryana.vercel.app/search/q/%E4%BD%A0%E5%A5%BD%E6%88%91%E7%9A%84%E5%AF%B9%E9%9D%A2%E7%94%B7%E5%8F%8B
- Log:

```
[ERROR] AttributeError: 'NoneType' object has no attribute 'find'
Traceback (most recent call last):
  File "/var/task/vc__handler__python.py", line 305, in vc_handler
    response = asgi_cycle(__vc_module.app, body)
  File "/var/task/vc__handler__python.py", line 208, in __call__
    loop.run_until_complete(asgi_task)
  File "/var/lang/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/var/task/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/var/task/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/var/task/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/var/task/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/var/task/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/var/task/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/var/task/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/var/task/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/var/task/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/var/task/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/var/task/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/var/task/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/var/task/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/var/task/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "./api/main.py", line 39, in search
    code, r = await search_func(query=query)
  File "/var/task/api/utils.py", line 23, in search_func
    f._get_search_results()
  File "/var/task/api/search.py", line 85, in _get_search_results
    title = result.find("h6", class_="text-primary title").find("a")
```

**Comment by leonguyen52** [comment]
I fixed it with following changes in search.py

`# search results handler
    def _get_search_results(self) -> None:
        results = self._get_container()  # get the search results

        _dramas = []
        _people = []

        for result in results:
            title_elem = result.find("h6", class_="text-primary title")
            if title_elem is None:
                continue  # skip if title is not found

            r = {}
            title = title_elem.text.strip()

            # extract the URL slug
            url_slug = title_elem.find("a").get("href")
            if url_slug is not None:
                r["slug"] = url_slug.replace("/", "", 1)
            else:
                continue  # skip this result if URL slug is not found

            # get the thumbnail
            _thumb = str(result.find("img", class_="img-responsive")["data-src"]).split(
                "/1280/"
            )
            if len(_thumb) > 1:
                r["thumb"] = _thumb[1]
            else:
                r["thumb"] = _thumb[0]

            if result.has_attr("id"):
                r["mdl_id"] = result["id"]

                # extract drama title
                r["title"] = title.strip()
                
                # drama ranking
                r["ranking"] = self._res_get_ranking(result)

                # specific drama info
                r["type"], r["year"], r["series"] = self._res_get_year_info(result)

                _dramas.append(r)
                continue

            # it can only be a person otherwise,
            r["name"] = title.strip()
            r["nationality"] = result.find("div", class_="text-muted").text.strip()
            _people.append(r)`

**Comment by tbdsux** [comment]
Thank you for reporting this problem. 

Your solutions looks good to me, please open a PR so I can merge your changes and thank you very much.
